---
title: "Merging Census Data"
author: "Casey Schmidt"
date: "2023-12-03"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dependency}
library(dplyr)
library(readxl)
library(tidyr)
library(lubridate)
```

This chunk of code is reading in and manipulating the census data so it matches the CDC data in order to merge. 
```{r census data}
dataCensus = read_xlsx("Census_Data.xlsx")
colnames(dataCensus) = c("Race", "Age", "Gender", "y2020", "y2021", "y2022")

# Calculating the inflation / deflation factor for the populations across years 
inFactor = dataCensus$y2020 / dataCensus$y2021

dataCensus$y2019 = ceiling(dataCensus$y2020 * inFactor)
dataCensus$y2018 = ceiling(dataCensus$y2019 * inFactor)

colnames(dataCensus) = c("Race", "Age", "Gender", "2020", "2021", "2022", "2019", "2018") 

dataCensus$Race = ifelse(dataCensus$Race == "Black", "Black or African American", dataCensus$Race)

# Pivot data to long format to match death data
dataCensus_final = select(dataCensus, -"2022") %>%
  pivot_longer(cols = c("2018", "2019", "2020", "2021"), 
               names_to = "Year", 
               values_to = "Population")

dataCensus_final$Year = as.numeric(dataCensus_final$Year)

```

Manipulating the CDC data and merging it with the census data. Also, manipulating the dates into a numeric format to make an indicator of COVID-19. 
```{r death data}
# Extract year from Month column to match 
dataMergedAge = read.csv("MergedData.csv")
dataMergedAge$year = lubridate::dmy(paste0("01 ", dataMergedAge$Month)) %>%
  lubridate::year()

# Match column names to census data
dataMergedAge = select(dataMergedAge, by = -"X")
colnames(dataMergedAge) = c("Race", "Gender", "Cause_of_Death", "Month", "Age", "Deaths", "Year")

dataFinal  = left_join(dataMergedAge, dataCensus_final, by = c("Year", "Age", "Gender", "Race"))


dataFinal[dataFinal$Deaths == max(dataFinal$Deaths, na.rm = TRUE),]

dates = lubridate::dmy(paste0("01 ", dataFinal$Month))

yearsData = lubridate::year(dates) - 2017 # subtract 2017 to adjust for first year being 2018
monthsData = lubridate::month(dates) # Extract month in number

dataFinal$months.numeric = 12 * (year(dates)-2018) + month(dates)

dataFinal$COVID = ifelse(dataFinal$months.numeric < 27, 0, 1)

# write.csv(dataFinal, "finalModelData.csv")



```

\newpage

```{r}
library(knitr)
fivedata = read.csv("fiveYearData.csv")
set.seed(625)
sampleData = sample_n(select(fivedata, by = c("Five.Year.Age.Groups", "Single.Race.6", "Drug.Alcohol.Induced", "Month", "Deaths", "Population")), 10)
colnames(sampleData) = c("Age", "Race", "Cause of Death", "Month", "Deaths", "Population")
knitr::kable(sampleData)
```

