---
title: "modelBuild"
author: "Caitlin Seibel"
date: "2023-12-04"
output: pdf_document
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(lmtest)
library(ggplot2)
library(car)
library(knitr)
```


```{r loadData}
final <- read.csv("finalModelData.csv")

final$Race <- relevel(as.factor(final$Race), ref = "White")
final$Gender <- relevel(as.factor(final$Gender), ref = "M")
final$Cause_of_Death <- relevel(as.factor(final$Cause_of_Death), ref = "All other non-drug and non-alcohol causes")
final$Age <- relevel(as.factor(final$Age), ref = "Under 5 years")
final$COVID <- as.factor(final$COVID)

```


```{r}
#check for na values
sum(is.na(final))

#looking at distribution of response/ check for overdispersion and excess zeros
summary(final$Deaths, na.rm = T)
hist(final$Deaths)
ggplot(final, aes(x = Deaths)) + 
  geom_histogram(binwidth = 5000) +
  ggtitle("Histogram of Deaths")

length(final[final$Deaths == 0,]) #check for excess zeros

mean(final$Deaths, na.rm = T)
var(final$Deaths, na.rm = T)

```
```{r model}
#first model: no interactions ----
#first try Poisson
modelP1 <- glm(Deaths ~ Cause_of_Death + Gender + Age + Race + COVID + offset(log(Population)),
               family = "poisson"(link = "log"),
               data = final)
summary(modelP1)
anova(modelP1)

#check for overdispersion pt 2
modelP1$deviance/modelP1$df.residual #111.4576 > 1, so we have an issue with overdispersion


#now try Neg Binomial
modelNB1 <- glm.nb(Deaths ~ Cause_of_Death + Gender + Age + Race + COVID + offset(log(Population)), 
                 link = log,
                 data = final)

summary(modelNB1)
anova(modelNB1)
modelNB1$deviance/modelNB1$df.residual #1.083095 or approx = 1

```
```{r}
#next models: interactions
modelNB2 <- glm.nb(Deaths ~ Cause_of_Death + Gender + Age + Race + COVID + Cause_of_Death:COVID + offset(log(Population)), 
                 link = log,
                 data = final)

summary(modelNB2)
anova(modelNB2)
Anova(modelNB2)

modelNB2$deviance/modelNB2$df.residual

#check for improved model fit
lmtest::lrtest(modelNB1, modelNB2) #model with interactions has better fit

#trying more interaction terms between cause_of_death and demographic factors
modelNB3 <- glm.nb(Deaths ~ Cause_of_Death + Gender + Age + Race + COVID + Cause_of_Death:COVID + Cause_of_Death:Gender + Cause_of_Death:Race + offset(log(Population)), 
                 link = log,
                 data = final)
summary(modelNB3)
anova(modelNB3)
Anova(modelNB3)

lmtest::lrtest(modelNB1, modelNB3)

#model diagnostics:
NB2_vif <- vif(modelNB2)
kable(NB2_vif)

res <- residuals(modelNB2, type = 'pearson')
fitted <- modelNB2$fitted.values
df <- data.frame(res = res, fitted = fitted)
ggplot(df, aes(x = fitted, y = res)) + geom_point()

```

